"""empty message

Revision ID: 4b22e81192d0
Revises: 
Create Date: 2017-03-13 05:34:10.603096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b22e81192d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userimage', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('userfname', sa.String(length=256), nullable=True),
    sa.Column('userlname', sa.String(length=256), nullable=True),
    sa.Column('userage', sa.Integer(), nullable=True),
    sa.Column('usergender', sa.String(length=120), nullable=True),
    sa.Column('userbio', sa.String(length=256), nullable=True),
    sa.Column('usertime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
